version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  validate-terraform-config:
    docker: 
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Validate dev environment
          command: |
            cd infrastructure
            terraform init
            terraform validate
            terraform fmt -check
workflows:
  default:
    jobs:
      - validate-terraform-config
