version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
          
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone # TODO: Include in cache the "bin" directory
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint

workflows:
  default:
    jobs:
      - init
      - docker/publish:
          matrix:
            parameters:
              image: [$DOCKER_LOGIN/app]
              path: [app]
              docker-context: [app]
              deploy: [true]
              # We publish two images with different version tags:
              # - numbered version # - "latest"
              # - "latest"
              tag: ["$(<app/VERSION.txt)", "latest"]
              update-description: [false]
          requires: [init]
